### ISSUE TITLE
"show unfinished batches" incorrect?

### ISSUE THREAD

**Issue by joshplumley** [conturo-prototyping/pack-ship-demo#82]
@jarrilla Im not sure if Im thinking about this correctly, but when the "Show Unfinished Batches" is checked on the packing slip page, all data is show. When I click it so that it is no longer checked, the rows where "Fullfilled Qty" >== "Batch Qty" are removed from the list.

Should rename the option to "Show Finished Batches" so that when it is off, the  "Fullfilled Qty" >== "Batch Qty" rows are removed (as it is now)? And then maybe default the checkbox to unchecked?

**Comment by jarrilla** [comment]
So, I think initially we had 2 checkboxes
- [ ] Show Unfinished Batches
- [ ] Show Fulfilled Batches
'Unfinished' was meant to pull every work order (not just those in the queue)
'Fulfilled' exactly as you say above.

Unfinished has been important to us because we sometimes ship stuff that isn't fully routed (eg. customer needs whatever we have done, and doesn't want to wait for full qty).

[TL;DR]
If anything, I would prefer to add another checkbox to do as described here. Explicitly:
- **Show Unfinished Batches** this can be dead. The "ready to pack" behavior isn't encoded into this demo project as it requires full part routing.
- **Show Fulfilled Batches** if unchecked, remove rows s.t. `fulfilledQty >= batchQty`.
